---
title: "Lectures"
output: 
  html_document:
    toc: false
    toc_float: true
    collapsed: false
    number_sections: false
    toc_depth: 3
---

Before you start browsing through the material consider the following strategies: There are (at least) two ways to progress through this material, depending upon how much time you have to devote to it each week.

1. If you are self-paced with at least 10 hours a week to devote to learning R, I’d recommend adopting the schedule below, which is designed for an intense but doable semester-long course, one module per week.  It is intended to take the average graduate student roughly 10 hours per week to complete all required tasks.  However, some number of students will find programming to be more challenging and may take up to 15 hours per week. Some will fly through the material in 5.

2. If you are self-paced with limited free time, you can take a more relaxed pace by alternating weeks: in the first week in each pair, complete the DataCamp materials, and in the second week, complete the project.  

Modules 1 – 7 are fundamental R programming.  Modules 8 – 11 are traditional social scientific statistical analyses and visualization. Modules 12 – 15 are new data science skills. Module16 is a more advanced statistical analysss tecnique. I will update the list of Modules in the near future, so stay tuned for more.


```{r, message=FALSE, warning=FALSE, echo=FALSE}
#library(data.table)
library(readxl)
Lectures <- read_excel("LectureSpring2019.xlsx", sheet = 1, col_names = TRUE, col_types = NULL, na = "", skip = 0)
Lectures[is.na(Lectures)]<- " "
#Lectures <- fread("Lectures.csv")
knitr::kable(Lectures)

```

Resources:

1.	Neth, H. (2020).  Data Science for Psychologists.  Social Psychology and Decision Sciences, University of Konstanz, Germany.  Textbook and R package ds4psy (version 0.2.1, May 6, 2020).  eBook available at https://bookdown.org/hneth/ds4psy/;  R package at https://CRAN.R-project.org/package=ds4psy

2.	Navarro, D. (2019). Learning statistics with R: A tutorial for psychology students and other beginners. (Version 0.6.1, June 19, 2019). Danielle Navarro (bookdown translation: Emily Kothe) eBook available at https://learningstatisticswithr.com/book/

3.	Irizarry, R. (2019). Introduction to Data Science. Data Analysis and Prediction Algorithms with R. eBook available at https://rafalab.github.io/dsbook/

4.	Wickham, H. & Grolemund, G. (2017). R for Data Science Import, Tidy, Transform, Visualize, and Model Data. eBook available at https://r4ds.had.co.nz/ 

5.	Field, A., Miles, J., & Field, Z. (2012). Discovering Statistics Using R. London, UK: Sage Publications. 

6.	Silge, J. & Robinson, D. (2017). Text Mining with R: A Tidy Approach. eBook available at https://www.tidytextmining.com/

7.	Harrer, M., Cuijpers, P., Furukawa, T.A, & Ebert, D. D. (2019). Doing Meta-Analysis in R: A Hands-on Guide. eBook available at https://bookdown.org/MathiasHarrer/Doing_Meta_Analysis_in_R/. 

